blog/urls.py
from django.urls import path
from blog.views import (
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
 ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from jobs.views import my_jobs,result

from personal.views import (
	home_screen_view,
    first_page_view,
    job_search_view,
)

from scholarship_blog.views import scholarship_blog_view

from account.views import (
    employee_registration_view,
    company_registration_view,
    logout_view,
    login_view,
    employee_account_view,
    company_account_view,
	must_authenticate_view,
    register_option_view,
    employee_redirect_view,
    company_redirect_view,
    company_profile_view,
)

urlpatterns = [
    path('',first_page_view,name="first_page"),
    path('jobs/', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('must_authenticate_as_employee/', employee_redirect_view, name="employee_redirect"),
    path('must_authenticate_as_company/', company_redirect_view, name="company_redirect"),

    path('register/employee', employee_registration_view, name="register_employee"),
    path('register/company', company_registration_view, name="register_company"),

    path('register/company_update', company_account_view, name="update_company_account"),
    path('register/employee_update', employee_account_view, name="update_employee_account"),
    path('home/company_profile',company_profile_view,name="company_profile_account"),

    path('register_option/',register_option_view,name="register_option"),
    
    path('home/',my_jobs,name="jobs"),
    path('home/results/',result,name="job_results"),
    path('learn/',job_search_view,name='learn_page'),

    path('scholarship_data/',scholarship_blog_view,name='scholarship_blog'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver




class JobPost(models.Model):
	job_title 				= models.CharField(max_length=50, null=False, blank=False)
	job_type				= models.CharField(max_length=50,null=False,blank=False)

	job_description			= models.TextField(max_length=5000, null=False, blank=False)
	url						= models.CharField(max_length=100,null=False,blank=False)
	location				= models.CharField(max_length=40)
	position				= models.CharField(max_length=30,null=False,blank=False)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	contact_email 			= models.EmailField(max_length=60)
	company_name			= models.CharField(max_length=30)

	slug 					= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.job_title+" "+self.author.username



def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.job_title)

pre_save.connect(pre_save_blog_post_receiver, sender=JobPost)

blog/forms.py
from django import forms

from blog.models import JobPost


class CreateJobPostForm(forms.ModelForm):

	class Meta:
		model = JobPost
		fields = ['job_title','job_type','job_description','url','location','position','contact_email']


class UpdateJobPostForm(forms.ModelForm):

	class Meta:
		model = JobPost
		fields = ['job_title','job_type','job_description','url','location','position','contact_email']

	def save(self, commit=True):
		job_post = self.instance
		job_post.job_title = self.cleaned_data['job_title']
		job_post.job_type = self.cleaned_data['job_type']
		job_post.job_description =self.cleaned_data['job_description']
		job_post.url = self.cleaned_data['url']
		job_post.location=self.cleaned_data['location']
		job_post.position=self.cleaned_data['position']
		job_post.contact_email=self.cleaned_data['contact_email']


		if commit:
			blog_post.save()
		return blog_post

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse

from blog.models import JobPost
from blog.forms import CreateJobPostForm, UpdateJobPostForm
from account.models import Account


def create_blog_view(request):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect('company_redirect')



	form = CreateJobPostForm(request.POST or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		context['success']="Successfully Updated"
		form = CreateJobPostForm()

	context['form'] = form

	return render(request, "blog/create_blog.html", context)


def detail_blog_view(request, slug):

	context = {}

	job_post = get_object_or_404(JobPost, slug=slug)
	context['job_post'] = job_post

	return render(request, 'blog/detail_blog.html', context)



def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("company_redirect")

	job_post = get_object_or_404(JobPost, slug=slug)

	if job_post.author != user:
		return HttpResponse('You are not the author of that post.')

	if request.POST:
		form = UpdateJobPostForm(request.POST or None, instance=job_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			job_post = obj

	form = UpdateJobPostForm(
			initial = {
					"job_title": job_post.job_title,
					"job_type": job_post.job_type,
					"job_description": job_post.job_description,
					"url":job_post.url,
					"location":job_post.location,
					"position":job_post.position,
					"job_description":job_post.job_description,

			}
		)

	context['form'] = form
	return render(request, 'blog/edit_blog.html', context)


def get_job_post_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = JobPost.objects.filter(
				Q(job_title__icontains=q) | 
				Q(job_description__icontains=q)|
				Q(job_type__icontains=q)|
				Q(location__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

blog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

blog/templates/blog/snippets/blog_post_snippet.html
<style type="text/css">

.grid{
	display: grid;
	grid-template-columns: 20% 80%;
	grid-template-areas: 
	"filter main";
	height: 100vh;
	margin-top:64px;
	margin-left:0px;
	left:0;
	top:64px;
	align-items: center;
  	justify-content: center;
}


.filter{
	margin:auto;
	position: fixed;
	grid-area:filter;
	/*float:left;*/
	background-color: #ffffff;
	width:20%;
	height: 100%; 

}

.filter h3{
	text-align:left;
	margin-left: 24px;
	font-weight: 400;

}

.fa-2x{
	margin-top: 13px;
	margin-right: 40px;
}

.main{

	/*background: transparent linear-gradient(220deg, #FF000091 0%, #FF9900 100%) 0% 0%;*/
	grid-area:main;
	/*float:right;*/
	height:100%;
	text-align: left;
}

.main h2{
	margin-top: 50px;
	margin-left: 120px;
	letter-spacing: 0;
	color: #FFFFFF;
}

.filter-types{
	margin-top: 24px; 
	display: flex;
	align-items: center;
	justify-content: center;
}
.filter-types li{
	margin:16px 0; 
}


.content{
	background-color: #FFFFFF;
	border-radius: 42px;
	box-shadow: 0px 1px 3px #00000029;
	width:80%;
	height:80px; 
	margin:56px auto;
	text-align: left;
}

.content-heading{
	margin-left: 120px;
	padding-top:10px;

}

.sub-content{
	margin-left: 120px;
	padding-top:10px;
}

.disable{
	display: none;
}
</style>


<div class="grid">
		<!-- <div class="filter">
			<h3>Sort by</h3>
			<hr>
			<div class="filter-types">
				<ul>
					<li><input type="checkbox" name="inter">Intern</li>
					<li><input type="checkbox" name="full-time">Full Time</li>
					<li><input type="checkbox" name="student">Student</li>
					<li><input type="checkbox" name="work-from-home">Work From Home</li>
					<li><input type="checkbox" name="location">Location</li>
				</ul>
			</div>
				<div class="disable">
					<form>
					<div><label for="find-location">Enter The Location</label></div>
					<input type="search" name="find-location" placeholder="Patna">
					<button type="submit" class="submit-btn">Find Jobs</button>
					</form>
				</div>
		</div> -->


{% if blog_post %}
<!-- <div class="container">
	<div class="row"> -->
		<!-- Blog Post
		<div class="card m-auto">
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title">{{blog_post.job_title}}</h2>
				</a>
				<p class="card-text">{{blog_post.job_description|safe|truncatechars:180}}</p>
				{% if blog_post.author == request.user %}
					<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author.username}}
			</div>
		</div>
	</div>
</div>  -->


		<div class="main">
			<h2>BEST SUITABLE JOBS FOR YOU</h2>
			<div class="content">
				<div class="content-heading">{{blog_post.job_title}}<i  id="icon" class="far fa-bookmark fa-2x float-right" onclick="myFunction(this.id)"></i></div>
				<div class="sub-content">{{blog_post.job_description}}</div>
			</div>
		</div>

{% else %}
<div class="main">
			<div class="content">
				<div class="content-heading">No results</div>
				<div class="sub-content">There were no results matching the search: "{{query}}"</div>
			</div>
		</div>

{% endif %}


</div>

    <!-- </div> -->
    <script>
        function myFunction(id) {
          console.log(id);
          var id=document.getElementById(id);
          id.classList.toggle("far");
          id.classList.toggle("fas");
          var xhr = new XMLHttpRequest();
          xhr.open('GET', 'sample.txt', true);
          xhr.onprogress = function(){
        console.log('READYSTATE: ', xhr.readyState);
      }
      
      xhr.onreadystatechange = function(){
        console.log('READYSTATE: ', xhr.readyState);
        if(this.readyState == 4 && this.status == 200){
          console.log(this.responseText);
        }
      }

      xhr.send();

        }
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>