blog/urls.py
from django.urls import path
from blog.views import (
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
 ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from jobs.views import my_jobs,result

from personal.views import (
	home_screen_view,
    first_page_view,
    job_search_view,
)

from scholarship_blog.views import scholarship_blog_view

from account.views import (
    employee_registration_view,
    company_registration_view,
    logout_view,
    login_view,
    employee_account_view,
    company_account_view,
	must_authenticate_view,
    register_option_view,
    employee_redirect_view,
    company_redirect_view,
    company_profile_view,
)

urlpatterns = [
    path('',first_page_view,name="first_page"),
    path('jobs/', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('must_authenticate_as_employee/', employee_redirect_view, name="employee_redirect"),
    path('must_authenticate_as_company/', company_redirect_view, name="company_redirect"),

    path('register/employee', employee_registration_view, name="register_employee"),
    path('register/company', company_registration_view, name="register_company"),

    path('register/company_update', company_account_view, name="update_company_account"),
    path('register/employee_update', employee_account_view, name="update_employee_account"),
    path('home/company_profile',company_profile_view,name="company_profile_account"),

    path('register_option/',register_option_view,name="register_option"),
    
    path('home/',my_jobs,name="jobs"),
    path('home/results/',result,name="job_results"),
    path('learn/',job_search_view,name='learn_page'),

    path('scholarship_data/',scholarship_blog_view,name='scholarship_blog'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scholarship_blog/models.py
from django.db import models

# Create your models here.
class ScholarShip(models.Model):

	scholarship_name	= models.CharField(max_length=60)
	scholarship_link	=models.CharField(max_length=80)
	image				=models.CharField(max_length=80)
	details				=models.CharField(max_length=200)
	apply_data			=models.CharField(max_length=25)
	time				=models.CharField(max_length=25)


	def __str__(self):
		return self.scholarship_name

scholarship_blog/views.py
from django.shortcuts import render
from scholarship_blog.models import ScholarShip
# Create your views here.


def scholarship_blog_view(requests):
	context={}
	scholarships =ScholarShip.objects.all()
	print(scholarships)
	context['scholarships']=scholarships
	return render(requests,'scholarship_blog/scholarship.html',context)

scholarship_blog/templates/scholarship_blog/scholarship.html
<!doctype html>

{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,700,800&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'header1.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'courses.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'scholarship.css'%}">

    <title>Scholarship</title>

    <style type="text/css">
      .img-fluid{
        height:250px;
        width: 250px;
        overflow: hidden;
        margin-bottom: 24px;
      }
    </style>
  </head>
  <body>
   <header>
      <nav class="navbar navbar-expand-lg fixed-top ">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="">LOGO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'jobs' %}">Home<span class="sr-only">(current)</span></a>
            </li>
             <li class="nav-item ">
              <a class="nav-link" href="{% url 'home' %}">Learn </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'scholarship_blog' %}">Schloarship</a>
            </li>

            {% if request.user.is_employee %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'company_redirect' %}">Post Job</a>
            </li>
            {% else %}
             <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:create' %}">Post Job</a>
            </li>

            {% endif %}


              {% if request.user.is_employee %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'update_employee_account' %}">Account</a>
            </li>
              {% else %}
               <li class="nav-item">
              <a class="nav-link" href="{% url 'company_profile_account' %}">Account</a>
            </li>
              {% endif %}
      
   


            </li>
          </ul>
        </div>
      </nav>
    </header>

    <div class="container">
      <h4>By Indian Government</h4>
      <div class="row">

        {% for scholarship in scholarships %}
        <div class="col-md-3 col-sm-6">
          <div class="card">
            <div class="card-block text-center">
              <img src="{{ scholarship.image }}" class="img-fluid">
              <div class="card-title">
                <h4>{{ scholarship.scholarship_name }}</h4>
              </div>
              <div class="card-text">
                <p>{{ scholarship.details }}</p>
              </div> 
            </div>
          </div>          
        </div>

        {% endfor %}
    
      </div>


    </div>







    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>